INSERT INTO account (name, email, role, password) VALUES
('Nguyễn Văn Mạnh', 'nguyenvanmanh@example.com', 'lecturer', 'password1'),
('Trần Thị Hương', 'tranthihuong@example.com', 'lecturer', 'password2'),
('Phạm Minh Tuấn', 'phamminhtuan@example.com', 'lecturer', 'password3'),
('Lê Thị Mai', 'lethimai@example.com', 'lecturer', 'password4'),
('Hoàng Văn Hùng', 'hoangvanhung@example.com', 'lecturer', 'password5'),
('Trần Minh Hải', 'tranminhhai@example.com', 'lecturer', 'password6'),
('Nguyễn Thị Lan', 'nguyenthilan@example.com', 'lecturer', 'password7'),
('Phan Thanh Tùng', 'phanthanhtung@example.com', 'lecturer', 'password8'),
('Ngô Hải Yến', 'ngohaiyen@example.com', 'lecturer', 'password9'),
('Vũ Thị Hà', 'vuthiha@example.com', 'lecturer', 'password10'),
('Nguyễn Thùy Linh', 'linh@example.com', 'lecturer', 'password11');

-- INSERT INTO task (name, group_id, progress, deadline) VALUES
-- ('Task 1', 1, 0.2, '2024-03-31 09:00:00'),
-- ('Task 2', 2, 0.4, '2024-04-05 14:00:00'),
-- ('Task 3', 3, 0.6, '2024-04-10 12:00:00'),
-- ('Task 4', 4, 0.8, '2024-04-15 16:00:00'),
-- ('Task 5', 5, 1.0, '2024-04-20 10:00:00'),
-- ('Task 6', 1, 0.3, '2024-04-25 11:00:00'),
-- ('Task 7', 2, 0.5, '2024-04-30 13:00:00'),
-- ('Task 8', 3, 0.7, '2024-05-05 15:00:00'),
-- ('Task 9', 4, 0.9, '2024-05-10 17:00:00'),
-- ('Task 10', 5, 1.0, '2024-05-15 18:00:00');

INSERT INTO criterion (name, description) VALUES
('Formulation', 'The clarity and specificity of the problem statement.'),
('Methodology', 'The appropriateness and effectiveness of the research method.'),
('Results', 'The quality and significance of the research findings.'),
('Discussion', 'The depth and insightfulness of the research discussion.'),
('References', 'The relevance and reliability of the cited sources.'),
('Presentation', 'The organization and delivery of the research presentation.'),
('Creativity', 'The originality and innovation of the research work.'),
('Relevance', 'The significance and applicability of the research topic.'),
('Quality', 'The overall quality and coherence of the research work.'),
('Contribution', 'The contribution and impact of the research to the field.'),
('Analysis', 'The thoroughness and accuracy of the data analysis.'),
('Interpretation', 'The clarity and insightfulness of the data interpretation.'),
('Evaluation', 'The critical evaluation of the research methods and results.'),
('Synthesis', 'The integration and synthesis of the research findings.'),
('Conclusion', 'The strength and relevance of the research conclusion.'),
('Recommendation', 'The practical and actionable recommendations for future research.'),
('Organization', 'The logical and coherent structure of the research paper.'),
('Clarity', 'The clarity and precision of the writing and argumentation.'),
('Grammar', 'The correctness and fluency of the language use.'),
('Style', 'The consistency and appropriateness of the writing style.'),
('Formatting', 'The adherence to formatting guidelines and standards.'),
('Citation', 'The proper citation and referencing of sources.'),
('Acknowledgment', 'The acknowledgment of contributions and support.'),
('Ethics', 'The adherence to ethical standards and guidelines.'),
('Originality', 'The originality and authenticity of the research work.'),
('Validity', 'The validity and reliability of the research findings.'),
('Reliability', 'The reliability and consistency of the research results.'),
('Generalization', 'The generalizability and applicability of the research findings.'),
('Limitation', 'The identification and discussion of research limitations.'),
('Implication', 'The implications and significance of the research findings.'),
('Future Work', 'The suggestions and directions for future research.'),
('Impact', 'The potential impact and significance of the research outcomes.'),
('Innovation', 'The innovation and novelty of the research approach.'),
('Contribution', 'The contribution and value of the research to the field.'),
('Significance', 'The significance and relevance of the research topic.'),
('Relevance', 'The relevance and applicability of the research findings.'),
('Quality', 'The quality and rigor of the research methodology.'),
('Validity', 'The validity and reliability of the research results.'),
('Reliability', 'The reliability and consistency of the research findings.'),
('Generalization', 'The generalizability and transferability of the research outcomes.'),
('Limitation', 'The identification and discussion of research limitations.'),
('Implication', 'The implications and practical significance of the research.'),
('Future Work', 'The suggestions and directions for future research.'),
('Impact', 'The potential impact and contribution of the research work.'),
('Innovation', 'The innovation and creativity of the research approach.'),
('Contribution', 'The contribution and value of the research to the field.'),
('Significance', 'The significance and importance of the research topic.'),
('Relevance', 'The relevance and applicability of the research findings.'),
('Quality', 'The quality and rigor of the research methodology.'),
('Validity', 'The validity and reliability of the research results.'),
('Reliability', 'The reliability and consistency of the research findings.'),
('Generalization', 'The generalizability and transferability of the research outcomes.'),
('Limitation', 'The identification and discussion of research limitations.'),
('Implication', 'The implications and practical significance of the research.'),
('Future Work', 'The suggestions and directions for future research.'),
('Impact', 'The potential impact and contribution of the research work.'),
('Innovation', 'The innovation and creativity of the research approach.'),
('Contribution', 'The contribution and value of the research to the field.'),
('Significance', 'The significance and importance of the research topic.'),
('Relevance', 'The relevance and applicability of the research findings.'),
('Quality', 'The quality and rigor of the research methodology.'),
('Validity', 'The validity and reliability of the research results.'),
('Reliability', 'The reliability and consistency of the research findings.'),
('Generalization', 'The generalizability and transferability of the research outcomes.'),
('Limitation', 'The identification and discussion of research limitations.'),
('Implication', 'The implications and practical significance of the research.'),
('Future Work', 'The suggestions and directions for future research.'),
('Impact', 'The potential impact and contribution of the research work.'),
('Innovation', 'The innovation and creativity of the research approach.'),
('Contribution', 'The contribution and value of the research to the field.'),
('Significance', 'The significance and importance of the research topic.'),
('Relevance', 'The relevance and applicability of the research findings.'),
('Quality', 'The quality and rigor of the research methodology.'),
('Validity', 'The validity and reliability of the research results.'),
('Reliability', 'The reliability and consistency of the research findings.'),
('Generalization', 'The generalizability and transferability of the research outcomes.'),
('Limitation', 'The identification and discussion of research limitations.'),
('Implication', 'The implications and practical significance of the research.'),
('Future Work', 'The suggestions and directions for future research.'),
('Impact', 'The potential impact and contribution of the research work.'),
('Innovation', 'The innovation and creativity of the research approach .'),
('Contribution', 'The contribution and value of the research to the field.'),
('Significance', 'The significance and importance of the research topic.'),
('Relevance', 'The relevance and applicability of the research findings.'),
('Quality', 'The quality and rigor of the research methodology.'),
('Validity', 'The validity and reliability of the research results.'),
('Reliability', 'The reliability and consistency of the research findings.'),
('Generalization', 'The generalizability and transferability of the research outcomes.'),
('Limitation', 'The identification and discussion of research limitations.'),
('Implication', 'The implications and practical significance of the research.'),
('Future Work', 'The suggestions and directions for future research.'),
('Impact', 'The potential impact and contribution of the research work.'),
('Innovation', 'The innovation and creativity of the research approach.'),
('Contribution', 'The contribution and value of the research to the field.'),
('Significance', 'The significance and importance of the research topic.'),
('Relevance', 'The relevance and applicability of the research findings.');



INSERT INTO "group" (name) VALUES
('Group 1'),
('Group 2'),
('Group 3'),
('Group 4'),
('Group 5'),
('Group 6'),
('Group 7'),
('Group 8'),
('Group 9'),
('Group 10'),
('Group 11'),
('Group 12'),
('Group 13'),
('Group 14'),
('Group 15'),
('Group 16'),
('Group 17'),
('Group 18'),
('Group 19'),
('Group 20'),
('Group 21'),
('Group 22'),
('Group 23'),
('Group 24'),
('Group 25'),
('Group 26'),
('Group 27'),
('Group 28'),
('Group 29'),
('Group 30'),
('Group 31'),
('Group 32'),
('Group 33'),
('Group 34'),
('Group 35'),
('Group 36'),
('Group 37'),
('Group 38'),
('Group 39'),
('Group 40'),
('Group 41'),
('Group 42'),
('Group 43'),
('Group 44'),
('Group 45'),
('Group 46'),
('Group 47'),
('Group 48'),
('Group 49'),
('Group 50'),
('Group 51'),
('Group 52'),
('Group 53'),
('Group 54'),
('Group 55'),
('Group 56'),
('Group 57'),
('Group 58'),
('Group 59'),
('Group 60'),
('Group 61'),
('Group 62'),
('Group 63'),
('Group 64'),
('Group 65'),
('Group 66'),
('Group 67'),
('Group 68'),
('Group 69'),
('Group 70'),
('Group 71'),
('Group 72'),
('Group 73'),
('Group 74'),
('Group 75'),
('Group 76'),
('Group 77'),
('Group 78'),
('Group 79'),
('Group 80'),
('Group 81'),
('Group 82'),
('Group 83'),
('Group 84'),
('Group 85'),
('Group 86'),
('Group 87'),
('Group 88'),
('Group 89'),
('Group 90'),
('Group 91'),
('Group 92'),
('Group 93'),
('Group 94'),
('Group 95'),
('Group 96'),
('Group 97'),
('Group 98'),
('Group 99'),
('Group 100'),
('Group 101'),
('Group 102'),
('Group 103'),
('Group 104'),
('Group 105'),
('Group 106'),
('Group 107'),
('Group 108'),
('Group 109'),
('Group 110'),
('Group 111'),
('Group 112'),
('Group 113'),
('Group 114'),
('Group 115'),
('Group 116'),
('Group 117'),
('Group 118'),
('Group 119'),
('Group 120'),
('Group 121'),
('Group 122'),
('Group 123'),
('Group 124'),
('Group 125'),
('Group 126'),
('Group 127'),
('Group 128'),
('Group 129'),
('Group 130'),
('Group 131'),
('Group 132'),
('Group 133'),
('Group 134'),
('Group 135'),
('Group 136'),
('Group 137'),
('Group 138'),
('Group 139'),
('Group 140'),
('Group 141'),
('Group 142'),
('Group 143'),
('Group 144'),
('Group 145'),
('Group 146'),
('Group 147'),
('Group 148'),
('Group 149'),
('Group 150'),
('Group 151'),
('Group 152'),
('Group 153'),
('Group 154'),
('Group 155'),
('Group 156'),
('Group 157'),
('Group 158'),
('Group 159'),
('Group 160'),
('Group 161'),
('Group 162'),
('Group 163'),
('Group 164'),
('Group 165'),
('Group 166'),
('Group 167'),
('Group 168'),
('Group 169'),
('Group 170'),
('Group 171'),
('Group 172'),
('Group 173'),
('Group 174'),
('Group 175'),
('Group 176'),
('Group 177'),
('Group 178'),
('Group 179'),
('Group 180'),
('Group 181'),
('Group 182'),
('Group 183'),
('Group 184'),
('Group 185'),
('Group 186'),
('Group 187'),
('Group 188'),
('Group 189'),
('Group 190'),
('Group 191'),
('Group 192'),
('Group 193'),
('Group 194'),
('Group 195'),
('Group 196'),
('Group 197'),
('Group 198'),
('Group 199'),
('Group 200');


INSERT INTO technology_category (name) VALUES
('C++'),
('Java'),
('Python'),
('JavaScript'),
('HTML/CSS'),
('SQL'),
('NoSQL'),
('Blockchain'),
('Machine Learning'),
('Artificial Intelligence'),
('Cloud Computing'),
('Internet of Things'),
('Web Development'),
('Mobile Development'),
('Data Analysis'),
('Network Security'),
('Data Visualization'),
('Smart Contracts'),
('Natural Language Processing'),
('Front-end Development'),
('Back-end Development'),
('iOS Development'),
('Android Development'),
('Game Development'),
('Embedded Systems'),
('DevOps'),
('UI/UX Design'),
('Software Testing'),
('Database Management'),
('Big Data'),
('Cybersecurity'),
('Digital Marketing'),
('E-commerce');


INSERT INTO technology_requirement (name, description) VALUES
('Front-end Development', 'Develop user interfaces for websites or web applications.'),
('Neural Networks', 'Implement neural network models for machine learning tasks.'),
('iOS App Development', 'Create mobile applications for iOS devices.'),
('Data Visualization', 'Represent data in graphical or pictorial format for easy understanding.'),
('Network Security', 'Ensure the security of computer networks from unauthorized access or attacks.'),
('Smart Contracts', 'Write smart contracts for blockchain applications.'),
('Natural Language Processing', 'Analyze and process natural language data for AI applications.'),
('Cloud Infrastructure', 'Set up and manage cloud-based infrastructure for applications or services.'),
('IoT Device Programming', 'Develop software for Internet of Things devices.'),
('Data Analysis', 'Analyze large datasets to extract useful insights and patterns.'),
('Web Development', 'Build websites or web applications using HTML, CSS, and JavaScript.'),
('Machine Learning', 'Develop algorithms that enable computers to learn from data and make predictions.'),
('Artificial Intelligence', 'Create intelligent systems that can perform tasks that typically require human intelligence.'),
('Mobile App Development', 'Design and develop mobile applications for smartphones or tablets.'),
('Blockchain Technology', 'Implement blockchain solutions for secure and transparent transactions.'),
('Database Management', 'Organize and manage data in databases for efficient storage and retrieval.'),
('Cybersecurity', 'Protect computer systems and networks from cyber threats and attacks.'),
('Software Testing', 'Test software applications to ensure they meet quality and performance standards.'),
('UI/UX Design', 'Design user interfaces and experiences for digital products or services.'),
('DevOps', 'Combine software development and IT operations to improve collaboration and productivity.'),
('Big Data Analytics', 'Analyze and interpret large and complex datasets to uncover hidden patterns or trends.'),
('Digital Marketing', 'Promote products or services using digital channels and technologies.'),
('E-commerce Development', 'Create online shopping platforms for buying and selling goods or services.'),
('Healthcare Technology', 'Develop technology solutions for improving healthcare delivery and patient outcomes.'),
('Finance Technology', 'Innovate financial services and products using technology and data.'),
('Educational Technology', 'Enhance teaching and learning experiences through technology tools and resources.'),
('Agricultural Technology', 'Apply technology to improve agricultural practices and increase productivity.'),
('Environmental Technology', 'Develop solutions for environmental challenges and sustainability.'),
('Social Media Management', 'Manage social media accounts and content to engage with audiences.'),
('Gaming Industry', 'Create video games for entertainment or educational purposes.'),
('Entertainment Industry', 'Produce content for movies, TV shows, music, or other forms of entertainment.'),
('Automotive Industry', 'Design and develop vehicles, components, or systems for the automotive sector.'),
('Retail Industry', 'Manage retail operations and customer experiences in physical or online stores.'),
('Travel Industry', 'Provide services and experiences for travelers and tourists.'),
('Real Estate Industry', 'Buy, sell, or rent properties and manage real estate transactions.'),
('Fashion Industry', 'Design, produce, and market clothing, accessories, or footwear.'),
('Food Industry', 'Prepare, cook, and serve food and beverages in restaurants or food establishments.'),
('Sports Industry', 'Organize and promote sports events, teams, or activities.'),
('Music Industry', 'Create, perform, or distribute music content or products.'),
('Film Industry', 'Produce, direct, or act in movies, TV shows, or other visual media.'),
('TV Industry', 'Produce, broadcast, or distribute television programs or content.'),
('Art Industry', 'Create, exhibit, or sell visual or performing arts.'),
('Design Industry', 'Develop creative concepts and solutions for products, services, or experiences.'),
('Education Industry', 'Provide educational services, resources, or programs for students or learners.'),
('Healthcare Industry', 'Deliver medical care, services, or products to improve health and well-being.'),
('Finance Industry', 'Offer financial services, products, or advice to individuals or businesses.'),
('Technology Industry', 'Develop, manufacture, or sell technology products, services, or solutions.'),
('Automotive Industry', 'Design and develop vehicles, components, or systems for the automotive sector.'),
('Retail Industry', 'Manage retail operations and customer experiences in physical or online stores.'),
('Travel Industry', 'Provide services and experiences for travelers and tourists.'),
('Real Estate Industry', 'Buy, sell, or rent properties and manage real estate transactions.'),
('Fashion Industry', 'Design, produce, and market clothing, accessories, or footwear.'),
('Food Industry', 'Prepare, cook, and serve food and beverages in restaurants or food establishments.'),
('Sports Industry', 'Organize and promote sports events, teams, or activities.'),
('Music Industry', 'Create, perform, or distribute music content or products.'),
('Film Industry', 'Produce, direct, or act in movies, TV shows, or other visual media.'),
('TV Industry', 'Produce, broadcast, or distribute television programs or content.'),
('Art Industry', 'Create, exhibit, or sell visual or performing arts.'),
('Design Industry', 'Develop creative concepts and solutions for products, services, or experiences.'),
('Education Industry', 'Provide educational services, resources, or programs for students or learners.'),
('Healthcare Industry', 'Deliver medical care, services, or products to improve health and well-being.'),
('Finance Industry', 'Offer financial services, products, or advice to individuals or businesses.'),
('Technology Industry', 'Develop, manufacture, or sell technology products, services, or solutions.');


INSERT INTO thesis (account_id, group_id, name, score, deadline) VALUES
(1, 1, 'Web Application for Online Shopping', 0.0, '2024-03-31 09:00:00'),
(2, 2, 'Predictive Model for Stock Prices', 0.0, '2024-04-05 14:00:00'),
(3, 3, 'Mobile App for Health Monitoring', 0.0, '2024-04-10 12:00:00'),
(4, 4, 'Data Analysis for Marketing Strategies', 0.0, '2024-04-15 16:00:00'),
(5, 5, 'Network Security for E-commerce Websites', 0.0, '2024-04-20 10:00:00'),
(6, 6, 'Smart Contracts for Supply Chain Management', 0.0, '2024-04-25 11:00:00'),
(7, 7, 'Natural Language Processing for Chatbots', 0.0, '2024-04-30 13:00:00'),
(8, 8, 'Cloud Infrastructure for Online Services', 0.0, '2024-05-05 15:00:00'),
(9, 9, 'IoT Device Programming for Smart Homes', 0.0, '2024-05-10 17:00:00'),
(10, 10, 'Data Analysis for Business Intelligence', 0.0, '2024-05-15 18:00:00'),
(11, 11, 'Web Development for Social Networking', 0.0, '2024-05-20 19:00:00'),
(1, 12, 'Machine Learning for Image Recognition', 0.0, '2024-05-25 20:00:00'),
(2, 13, 'Artificial Intelligence for Robotics', 0.0, '2024-05-30 21:00:00'),
(3, 14, 'Mobile App for Fitness Tracking', 0.0, '2024-06-05 22:00:00'),
(4, 15, 'Blockchain Technology for Digital Assets', 0.0, '2024-06-10 23:00:00'),
(5, 16, 'Database Management for Data Warehousing', 0.0, '2024-06-15 00:00:00'),
(6, 17, 'Cybersecurity for Online Privacy', 0.0, '2024-06-20 01:00:00'),
(7, 18, 'Software Testing for Quality Assurance', 0.0, '2024-06-25 02:00:00'),
(8, 19, 'UI/UX Design for User Engagement', 0.0, '2024-06-30 03:00:00'),
(9, 20, 'DevOps for Continuous Integration', 0.0, '2024-07-05 04:00:00'),
(10, 21, 'Big Data Analytics for Business Insights', 0.0, '2024-07-10 05:00:00'),
(11, 22, 'Digital Marketing for Brand Promotion', 0.0, '2024-07-15 06:00:00'),
(1, 23, 'E-commerce Development for Online Stores', 0.0, '2024-07-20 07:00:00'),
(2, 24, 'Healthcare Technology for Patient Care', 0.0, '2024-07-25 08:00:00'),
(3, 25, 'Finance Technology for Investment Management', 0.0, '2024-07-30 09:00:00');




